# Import Libraries

Here, we import required libraries. The purpose of each package is as follows.

- glob: to find the data sets
- pandas: to parse csv
- matplotlib: to read ppm file
- cv2: to resize the read images
- os: general operations on path (e.g., os.path.dirname)
- numpy: general numerical operation
- sklearn: to split test data
- tensorflow: CNN

In [40]:
import glob
import pandas as pd
# import matplotlib
import matplotlib.pyplot as plt
# import matplotlib.image as mpimg
import cv2
import os
import numpy as np
from sklearn.model_selection import train_test_split
# from sklearn.metrics import confusion_matrix
import tensorflow as tf
from tensorflow.contrib.layers import flatten
# from pipeline import NewralNetwork, make_adam, Session, build_pipeline

# Read Data for Training

In [66]:
TRAIN_IMAGE_DIR = 'data/GTSRB_Final_Training_Images/GTSRB/Final_Training/Images/'

data_files = []
for train_file in glob.glob(os.path.join(TRAIN_IMAGE_DIR, '*/GT-*.csv')):
    folder = os.path.dirname(train_file)
    df = pd.read_csv(train_file, sep=';')
    df['Filename'] = df['Filename'].apply(lambda x: os.path.join(folder, x))
    data_files.append(df)

In [67]:
train_df = pd.concat(data_files, ignore_index=True)
train_df.head()

Filename  Width  Height  Roi.X1  \
0  data/GTSRB_Final_Training_Images/GTSRB/Final_T...     38      35       5   
1  data/GTSRB_Final_Training_Images/GTSRB/Final_T...     40      36       6   
2  data/GTSRB_Final_Training_Images/GTSRB/Final_T...     40      37       5   
3  data/GTSRB_Final_Training_Images/GTSRB/Final_T...     41      39       6   
4  data/GTSRB_Final_Training_Images/GTSRB/Final_T...     43      37       6   

   Roi.Y1  Roi.X2  Roi.Y2  ClassId  
0       5      33      30       31  
1       5      34      31       31  
2       5      34      32       31  
3       6      36      34       31  
4       5      38      32       31

In [84]:
def load_image(image_file):
    """
    Read image file into numpy array (RGB)
    """
    return plt.imread(image_file)

In [145]:
INPUT_SHAPE = (32, 32, 3)

def resize_image(image, shape=INPUT_SHAPE[:2]):
    return cv2.resize(image, shape)

loader = lambda image_file: resize_image(load_image(image_file))
load_all = np.vectorize(loader)

# Load The Data

In [156]:
X = train_df['Filename'].values
y = train_df['ClassId'].values

train_data_filenames, eval_data_filenames, train_labels, eval_labels = train_test_split(X, y, stratify=y, test_size=8000, random_state=0)
train_data = []
for f in train_data_filenames:
    train_data.append(loader(f))
train_data = np.array(train_data, dtype=float)
eval_data = []
for f in eval_data_filenames:
    eval_data.append(loader(f))
eval_data = np.array(eval_data, dtype=float) 
print(len(train_data))
print(len(eval_data))

31209
8000


In [142]:
#np.unique(train_data)
train_data.head

AttributeError: 'list' object has no attribute 'head'

# Main Function

## Training of the model

In [160]:
gtsrb_classifier = tf.estimator.Estimator(
    model_fn=cnn_model_fn, model_dir="/tmp/gtsrb_convnet_model")

# Set up logging for predictions
tensors_to_log = {"probabilities": "softmax_tensor"}
logging_hook = tf.train.LoggingTensorHook(
    tensors=tensors_to_log, every_n_iter=50)

# Train the model
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": train_data},
    y=train_labels,
    batch_size=100,
    num_epochs=None,
    shuffle=True)
gtsrb_classifier.train(
    input_fn=train_input_fn,
    steps=20000,
    hooks=[logging_hook])


INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/gtsrb_convnet_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x127e1f518>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/gtsrb_convnet_model/model.ckpt.
INFO:tensorflow

INFO:tensorflow:global_step/sec: 1.25799
INFO:tensorflow:probabilities = [[0.00961209 0.04275379 0.0568032  ... 0.01836062 0.01347492 0.01399498]
 [0.0082774  0.03469462 0.04543413 ... 0.01238074 0.01268274 0.00858661]
 [0.01878978 0.0255833  0.03300976 ... 0.01638716 0.01797376 0.01412671]
 ...
 [0.00596292 0.0508219  0.13322646 ... 0.02446701 0.0029958  0.00246199]
 [0.01817645 0.03458592 0.02957172 ... 0.02183006 0.01362973 0.01314261]
 [0.01761162 0.03072088 0.04280914 ... 0.02221676 0.0151155  0.01443174]] (40.712 sec)
INFO:tensorflow:loss = 3.5823607444763184, step = 701 (79.493 sec)
INFO:tensorflow:probabilities = [[0.01945578 0.03432644 0.02721125 ... 0.01913492 0.01645483 0.02078906]
 [0.01717967 0.03273084 0.0338758  ... 0.02688779 0.01632479 0.02206004]
 [0.02113716 0.02580692 0.02598742 ... 0.02179666 0.01992078 0.0220049 ]
 ...
 [0.01223096 0.02924758 0.04676444 ... 0.01314796 0.00754462 0.01197284]
 [0.00421732 0.03559675 0.12075649 ... 0.01050255 0.01049263 0.01893152]
 

INFO:tensorflow:loss = 2.994582414627075, step = 1401 (68.466 sec)
INFO:tensorflow:probabilities = [[0.01036878 0.01922297 0.02754498 ... 0.00258907 0.00147694 0.00109426]
 [0.00003073 0.00334351 0.02557221 ... 0.00812067 0.00000541 0.00083314]
 [0.00222609 0.04728179 0.0074796  ... 0.01725038 0.00718105 0.00441074]
 ...
 [0.00055006 0.00963961 0.05337203 ... 0.00144965 0.000425   0.00273349]
 [0.000252   0.00033585 0.00161629 ... 0.00039157 0.00000053 0.00012339]
 [0.00062202 0.02131969 0.0064325  ... 0.02042961 0.00031041 0.02526368]] (34.463 sec)
INFO:tensorflow:global_step/sec: 1.40181
INFO:tensorflow:probabilities = [[0.00246184 0.00727831 0.05948115 ... 0.00377686 0.00017572 0.00033985]
 [0.02795985 0.03704755 0.04755696 ... 0.01626081 0.00969761 0.01258713]
 [0.01248812 0.02310235 0.03164857 ... 0.01839068 0.00969613 0.01495441]
 ...
 [0.00007112 0.10397384 0.01230916 ... 0.00000793 0.         0.00000054]
 [0.00055334 0.00812384 0.01079362 ... 0.00457968 0.00018939 0.00009952]
 

INFO:tensorflow:global_step/sec: 0.97316
INFO:tensorflow:probabilities = [[0.01989972 0.01479577 0.01143933 ... 0.01010549 0.01895922 0.0085546 ]
 [0.01210953 0.0063066  0.00501952 ... 0.02592237 0.00509416 0.00589825]
 [0.00000715 0.01734089 0.49074105 ... 0.00000094 0.         0.00000001]
 ...
 [0.00025989 0.00633796 0.01008764 ... 0.00032875 0.00110175 0.00083467]
 [0.00000006 0.00010425 0.00031432 ... 0.00247898 0.         0.        ]
 [0.00001878 0.00117153 0.00086815 ... 0.00249017 0.00018847 0.0000316 ]] (44.292 sec)
INFO:tensorflow:loss = 1.4133938550949097, step = 2201 (102.755 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00000001 0.00000053 ... 0.00006099 0.         0.        ]
 ...
 [0.00000647 0.00008302 0.00001902 ... 0.00001934 0.00002075 0.00001448]
 [0.0001385  0.00119757 0.00085553 ... 0.0005602  0.00000331 0.00021815]

INFO:tensorflow:loss = 1.093658208847046, step = 2901 (84.691 sec)
INFO:tensorflow:probabilities = [[0.00001318 0.84465425 0.01910151 ... 0.00000729 0.00032224 0.00000199]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00776486 0.0262236  0.00362343 ... 0.01497539 0.00088951 0.00324381]
 ...
 [0.0013701  0.64931459 0.25941152 ... 0.00015407 0.00010749 0.00034806]
 [0.00216028 0.20196627 0.01003216 ... 0.00002806 0.00000235 0.00001927]
 [0.03348145 0.18163224 0.01523852 ... 0.00068322 0.00360961 0.00780862]] (39.219 sec)
INFO:tensorflow:global_step/sec: 1.32036
INFO:tensorflow:probabilities = [[0.00000001 0.         0.02052092 ... 0.00000015 0.00000023 0.        ]
 [0.00001772 0.00019098 0.00002888 ... 0.00000285 0.0000024  0.00005346]
 [0.0002859  0.03089859 0.00463442 ... 0.00000022 0.00000054 0.0000047 ]
 ...
 [0.00000009 0.00000044 0.00000025 ... 0.00000123 0.00003103 0.00000058]
 [0.00082307 0.00549558 0.00519261 ... 0.00003811 0.00000966 0.00002513]
 

INFO:tensorflow:global_step/sec: 1.48052
INFO:tensorflow:probabilities = [[0.00003954 0.00002101 0.99064689 ... 0.00000092 0.00000006 0.00000085]
 [0.00203406 0.00043033 0.0064364  ... 0.00008189 0.00009876 0.0001666 ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00000001 0.00000003 0.00000173 ... 0.00000005 0.00000313 0.00000013]
 [0.00000286 0.00000002 0.00000003 ... 0.00000019 0.         0.        ]
 [0.00900189 0.14857409 0.06328196 ... 0.00175828 0.00052144 0.00224108]] (34.027 sec)
INFO:tensorflow:loss = 0.8170825242996216, step = 3701 (67.546 sec)
INFO:tensorflow:probabilities = [[0.         0.00000012 0.         ... 0.         0.         0.00000001]
 [0.04016151 0.03508471 0.03104753 ... 0.00828335 0.02145817 0.00983611]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00000172 0.00003428 0.00003533 ... 0.00000179 0.00007575 0.00047168]
 [0.00001889 0.00074585 0.0025145  ... 0.00000639 0.00001    0.00009614]


INFO:tensorflow:loss = 0.7356947064399719, step = 4401 (74.754 sec)
INFO:tensorflow:probabilities = [[0.00066761 0.00106031 0.00743273 ... 0.00217091 0.00109604 0.00208253]
 [0.         0.         0.00000002 ... 0.00000036 0.00000004 0.00000009]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00005503 0.993589   0.0001269  ... 0.00000004 0.00000002 0.00000607]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]] (37.162 sec)
INFO:tensorflow:global_step/sec: 1.33025
INFO:tensorflow:probabilities = [[0.00013493 0.000239   0.00449563 ... 0.0000588  0.00000239 0.00001162]
 [0.         0.         0.         ... 0.         0.         0.00000005]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.00000001 0.         ... 0.00000008 0.99963516 0.00002947]
 [0.01379544 0.06326531 0.00321667 ... 0.0010802  0.00278316 0.0174301 ]


INFO:tensorflow:global_step/sec: 1.32475
INFO:tensorflow:probabilities = [[0.00000645 0.00165352 0.000612   ... 0.00000105 0.00000287 0.00000447]
 [0.         0.99999971 0.00000022 ... 0.         0.         0.        ]
 [0.         0.00000002 0.00000007 ... 0.         0.         0.        ]
 ...
 [0.00187104 0.00274052 0.00239757 ... 0.01065946 0.01987138 0.00400091]
 [0.011746   0.0458994  0.01614382 ... 0.00625307 0.01846857 0.02941028]
 [0.00000002 0.         0.00000004 ... 0.         0.         0.        ]] (38.095 sec)
INFO:tensorflow:loss = 0.6540879607200623, step = 5201 (75.483 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00000164 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]


INFO:tensorflow:loss = 0.37734153866767883, step = 5901 (75.592 sec)
INFO:tensorflow:probabilities = [[0.00000011 0.00002812 0.00000167 ... 0.         0.00000001 0.00000023]
 [0.00001769 0.00000065 0.00000001 ... 0.         0.         0.00000928]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.00000081 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.01864343 0.04036484 0.32216574 ... 0.01029092 0.00911714 0.02812847]] (37.743 sec)
INFO:tensorflow:global_step/sec: 1.32801
INFO:tensorflow:probabilities = [[0.0000013  0.00000537 0.00003456 ... 0.0000004  0.00000004 0.00000036]
 [0.00015886 0.00527525 0.0003802  ... 0.00271596 0.02674653 0.00852309]
 [0.0003093  0.999689   0.00000002 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.00000009 0.         0.        ]
 [0.00000003 0.94878466 0.04304741 ... 0.00000542 0.00000255 0.00000231]

INFO:tensorflow:global_step/sec: 1.32106
INFO:tensorflow:probabilities = [[0.         0.00000004 0.         ... 0.         0.         0.        ]
 [0.         0.00000018 0.         ... 0.         0.         0.        ]
 [0.04962856 0.05602265 0.03277721 ... 0.01145498 0.00267222 0.0202027 ]
 ...
 [0.         0.00000018 0.00000003 ... 0.00000434 0.         0.00000017]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00978388 0.00005999 0.00221204 ... 0.00000052 0.         0.00000002]] (38.218 sec)
INFO:tensorflow:loss = 0.23950031399726868, step = 6701 (75.697 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00071359 0.99928569 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00000002 0.00000001 0.00000016 ... 0.00000002 0.         0.        ]
 [0.         0.99965228 0.00000002 ... 0.         0.         0.        ]

INFO:tensorflow:loss = 0.14741599559783936, step = 7401 (75.446 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.01341361 0.0038133  0.00632812 ... 0.00001315 0.0000567  0.00003457]
 [0.00267588 0.00304959 0.00440256 ... 0.00059667 0.00419247 0.05834117]
 ...
 [0.00020499 0.00001262 0.00002649 ... 0.00000083 0.0000047  0.00014143]
 [0.00000001 0.00073157 0.00002134 ... 0.00000036 0.00009218 0.00000007]
 [0.         0.00000002 0.00000151 ... 0.         0.         0.        ]] (38.047 sec)
INFO:tensorflow:global_step/sec: 1.32417
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00012256 0.00003569 0.00082711 ... 0.00000004 0.00000003 0.00000121]
 ...
 [0.00000003 0.00000991 0.99751318 ... 0.         0.         0.        ]
 [0.00000694 0.0000075  0.00007939 ... 0.00001139 0.00007527 0.00003826]

INFO:tensorflow:global_step/sec: 1.32327
INFO:tensorflow:probabilities = [[0.00000021 0.00024558 0.00003138 ... 0.0000014  0.00000005 0.0000046 ]
 [0.00000047 0.00000689 0.00008708 ... 0.         0.         0.00000208]
 [0.00110763 0.00422431 0.18474945 ... 0.00003004 0.00087379 0.02835284]
 ...
 [0.00000006 0.00000082 0.00000109 ... 0.00000043 0.00000108 0.00000043]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000001 0.         0.00000081 ... 0.         0.         0.        ]] (38.256 sec)
INFO:tensorflow:loss = 0.31454747915267944, step = 8201 (75.567 sec)
INFO:tensorflow:probabilities = [[0.00010004 0.00244771 0.0006993  ... 0.00130709 0.00383829 0.00233693]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00084755 0.00105467 0.00039611 ... 0.00283361 0.00237462 0.00130523]
 ...
 [0.0016211  0.56250435 0.27795414 ... 0.00135212 0.00464245 0.001549  ]
 [0.00000022 0.00016395 0.00062696 ... 0.00002754 0.00000036 0.00048796]

INFO:tensorflow:loss = 0.1381434053182602, step = 8901 (75.033 sec)
INFO:tensorflow:probabilities = [[0.00251401 0.00652979 0.01201976 ... 0.0069679  0.00041982 0.00529225]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00308699 0.03031436 0.02950839 ... 0.00785454 0.00413423 0.00758966]
 ...
 [0.00193338 0.00709575 0.02563538 ... 0.00000381 0.00000053 0.00025031]
 [0.         0.00000021 0.00000179 ... 0.00000035 0.00000006 0.00000012]
 [0.00035908 0.00067989 0.00341735 ... 0.00117939 0.00040747 0.00105459]] (37.823 sec)
INFO:tensorflow:global_step/sec: 1.33245
INFO:tensorflow:probabilities = [[0.00000027 0.99928854 0.0000159  ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00213119 0.00384432 0.08296687 ... 0.00124341 0.00013474 0.00033931]


INFO:tensorflow:global_step/sec: 1.32527
INFO:tensorflow:probabilities = [[0.07730241 0.04255836 0.01524821 ... 0.00883192 0.00486354 0.01265286]
 [0.         0.00000004 0.00000044 ... 0.00000001 0.00000002 0.00000418]
 [0.         0.         0.00000005 ... 0.00000033 0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00004572 0.00068156 0.0003084  ... 0.0002689  0.00017322 0.00007846]] (37.959 sec)
INFO:tensorflow:loss = 0.12414401769638062, step = 9701 (75.461 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000001 0.00030152 0.99742278 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.0000003  0.97827695 0.00288695 ... 0.         0.         0.        ]

INFO:tensorflow:loss = 0.13989971578121185, step = 10401 (75.446 sec)
INFO:tensorflow:probabilities = [[0.         0.00000126 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00000009 0.00000005 0.         ... 0.         0.         0.00000001]
 [0.         0.0000006  0.         ... 0.         0.00000054 0.        ]
 [0.         0.00000012 0.         ... 0.00000001 0.         0.00000041]] (38.131 sec)
INFO:tensorflow:global_step/sec: 1.3204
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00000001 0.         ... 0.         0.         0.        ]
 [0.         0.         0.00000033 ... 0.99984476 0.         0.        ]
 ...
 [0.27629012 0.05333229 0.00076553 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]

INFO:tensorflow:global_step/sec: 1.31879
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00000496 0.9999942  ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00000001 0.0001282  ... 0.         0.         0.00000024]] (38.212 sec)
INFO:tensorflow:loss = 0.10911792516708374, step = 11201 (75.827 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.00006031 0.00001252 0.00000972 ... 0.00006172 0.9821564  0.00201348]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.00000164 0.00000006

INFO:tensorflow:global_step/sec: 1.32477
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.99998598 0.00000002 0.         ... 0.         0.         0.        ]
 [0.00000052 0.00001911 0.0000087  ... 0.00014521 0.00000002 0.00029912]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000083 0.00000443 0.00000186 ... 0.00000086 0.00000018 0.0000029 ]] (37.699 sec)
INFO:tensorflow:loss = 0.08831613510847092, step = 12001 (75.481 sec)
INFO:tensorflow:probabilities = [[0.00000722 0.00000792 0.00018006 ... 0.00035879 0.00001495 0.0000009 ]
 [0.         0.         0.00000088 ... 0.         0.         0.00000001]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.00000019 0.00000579 ... 0.0000269  0.         0.00000137]
 [0.         0.         0.         ... 0.         0.         0.        

INFO:tensorflow:loss = 0.12553752958774567, step = 12701 (75.353 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000005 0.00019346 0.00009401 ... 0.00002919 0.00005191 0.00004447]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00005187 0.00033488 0.00006979 ... 0.00003662 0.00146683 0.00547557]
 [0.00000004 0.00000031 0.00000036 ... 0.00000004 0.00002056 0.00592863]] (37.342 sec)
INFO:tensorflow:global_step/sec: 1.3222
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.00000001]
 [0.00001137 0.00001581 0.00030905 ... 0.00000323 0.00000227 0.00000501]
 [0.00000007 0.00000001 0.00000037 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000001 0.00205887 0.99748075 ... 0.         0.         0.        ]

INFO:tensorflow:global_step/sec: 1.32175
INFO:tensorflow:probabilities = [[0.00000177 0.00000842 0.00000169 ... 0.0000102  0.00000001 0.00000219]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000837 0.00267563 0.00005952 ... 0.00036749 0.00001103 0.0000375 ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99999999 ... 0.         0.         0.        ]] (37.583 sec)
INFO:tensorflow:loss = 0.20050406455993652, step = 13501 (75.657 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.99994293 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99999999 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        

INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.97353895 0.00003009 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.03064637 0.02458001 0.03737921 ... 0.01617187 0.00332827 0.00332069]] (37.527 sec)
INFO:tensorflow:Saving checkpoints for 14272 into /tmp/gtsrb_convnet_model/model.ckpt.
INFO:tensorflow:global_step/sec: 1.32101
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00004565 0.00001104 0.00001312 ... 0.00001027 0.00000084 0.00000132]
 ...
 [0.         0.         0.         ... 0.00000001 0.         0.        ]
 [0.         0.00000491 0.         ... 0.         0.99

INFO:tensorflow:global_step/sec: 1.32493
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.00001721 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.0244209  0.77242122 0.00400177 ... 0.00000797 0.00000034 0.00000869]
 [0.         0.         0.         ... 0.         0.00000004 0.00000005]
 [0.         0.         0.         ... 0.         0.         0.        ]] (37.423 sec)
INFO:tensorflow:loss = 0.08596497029066086, step = 15001 (75.473 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.00000001 ... 0.00000001 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        

INFO:tensorflow:loss = 0.13323092460632324, step = 15701 (75.562 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000057 0.19042381 0.00007548 ... 0.00000093 0.00001473 0.00010717]
 [0.         0.00000036 0.00000019 ... 0.         0.         0.        ]
 ...
 [0.         0.         1.         ... 0.         0.         0.        ]
 [0.0065566  0.00066776 0.00273503 ... 0.0036446  0.0003493  0.04853256]
 [0.         0.         0.         ... 0.         0.         0.        ]] (37.351 sec)
INFO:tensorflow:global_step/sec: 1.33822
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00000015 0.         0.00000003 ... 0.00000164 0.         0.00000005]
 [0.         0.         0.         ... 0.         0.         0.        

INFO:tensorflow:global_step/sec: 1.32858
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.00000416 ... 0.         0.         0.        ]
 [0.         0.14834264 0.82636615 ... 0.         0.         0.00000019]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000007 0.00000008 0.         ... 0.00000023 0.00000003 0.00000004]
 [0.         0.         0.         ... 0.         0.         0.        ]] (37.255 sec)
INFO:tensorflow:loss = 0.04495006427168846, step = 16501 (75.269 sec)
INFO:tensorflow:probabilities = [[0.         0.0000054  0.00068781 ... 0.         0.         0.00000001]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000089 0.00003374 0.00000061 ... 0.         0.         0.00000062

INFO:tensorflow:loss = 0.06573336571455002, step = 17201 (75.264 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00000036 0.         ... 0.         0.00000007 0.00017676]
 [0.         0.         0.         ... 0.00000003 0.00000008 0.00000031]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]] (38.261 sec)
INFO:tensorflow:global_step/sec: 1.31097
INFO:tensorflow:probabilities = [[0.0000036  0.00000025 0.00266894 ... 0.00000139 0.00000007 0.01118315]
 [0.00000107 0.00001328 0.00000412 ... 0.00000464 0.00000817 0.00000012]
 [0.00003595 0.00001356 0.00099642 ... 0.00014451 0.00005947 0.00016857]
 ...
 [0.         0.00000002 0.         ... 0.         0.99994008 0.00003813]
 [0.         0.         0.         ... 0.         0.         0.        

INFO:tensorflow:global_step/sec: 1.32702
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000012 0.00000001 0.         ... 0.00000007 0.00000024 0.00000003]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00000003 0.00002023 0.00000074 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.0000004  0.95166488 ... 0.         0.         0.        ]] (37.413 sec)
INFO:tensorflow:loss = 0.1177186444401741, step = 18001 (75.355 sec)
INFO:tensorflow:probabilities = [[0.00000159 0.0000235  0.00051551 ... 0.00000001 0.         0.00000001]
 [0.00053344 0.00002826 0.00588954 ... 0.00000287 0.0000568  0.00007895]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.00000001 ... 0.         0.         0.        ]
 [1.         0.         0.         ... 0.         0.         0.        ]

INFO:tensorflow:global_step/sec: 1.30299
INFO:tensorflow:probabilities = [[0.51719995 0.48279949 0.         ... 0.         0.         0.        ]
 [0.0000775  0.00087013 0.24132604 ... 0.00000009 0.00000002 0.00000011]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.000001   ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]] (38.588 sec)
INFO:tensorflow:loss = 0.04542580991983414, step = 18801 (76.745 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00000011 0.         ... 0.         0.         0.        ]
 [0.         0.00000002 0.00000071 ... 0.         0.         0.        ]
 ...
 [0.         0.99685668 0.00002224 ... 0.         0.         0.        ]
 [0.         0.0001634  0.00006608 ... 0.         0.         0.        

INFO:tensorflow:loss = 0.03267683833837509, step = 19501 (75.235 sec)
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000105 0.00000077 0.00021807 ... 0.00003834 0.00004103 0.00000126]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.00005585 0.00000159 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]] (38.093 sec)
INFO:tensorflow:global_step/sec: 1.31087
INFO:tensorflow:probabilities = [[0.00000048 0.00000499 0.00006382 ... 0.00000405 0.00000614 0.00008864]
 [0.         0.         0.         ... 0.00000027 0.         0.        ]
 [0.00010242 0.0106298  0.00750326 ... 0.00414879 0.00224553 0.00058105]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00000005 0.00003332 0.00012624 ... 0.         0.         0.00000001

NameError: name 'mnist_classifier' is not defined

## Evaluation of the learned

In [161]:
# Evaluate the model and print results
eval_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": eval_data},
    y=eval_labels,
    num_epochs=1,
    shuffle=False)
eval_results = gtsrb_classifier.evaluate(input_fn=eval_input_fn)
print(eval_results)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-05-16-02:24:15
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/gtsrb_convnet_model/model.ckpt-20000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2018-05-16-02:24:36
INFO:tensorflow:Saving dict for global step 20000: accuracy = 0.9775, global_step = 20000, loss = 0.10542794
{'accuracy': 0.9775, 'loss': 0.10542794, 'global_step': 20000}


In [ ]:
if __name__ == "__main__":
  tf.app.run()

# CNN Model

In [159]:
def cnn_model_fn(features, labels, mode):
  """Model function for CNN."""
  # Input Layer
  input_layer = tf.reshape(features["x"], [-1] + list(INPUT_SHAPE))

  # Convolutional Layer #1
  conv1 = tf.layers.conv2d(
      inputs=input_layer,
      filters=32,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu)

  # Pooling Layer #1
  pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[2, 2], strides=2)

  # Convolutional Layer #2 and Pooling Layer #2
  conv2 = tf.layers.conv2d(
      inputs=pool1,
      filters=64,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu)
  pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[2, 2], strides=2)

  # Dense Layer
  pool2_flat = tf.reshape(pool2, [-1, 8 * 8 * 64])
  dense = tf.layers.dense(inputs=pool2_flat, units=1024, activation=tf.nn.relu)
  dropout = tf.layers.dropout(
      inputs=dense, rate=0.4, training=mode == tf.estimator.ModeKeys.TRAIN)

  # Logits Layer
  logits = tf.layers.dense(inputs=dropout, units=43)

  predictions = {
      # Generate predictions (for PREDICT and EVAL mode)
      "classes": tf.argmax(input=logits, axis=1),
      # Add `softmax_tensor` to the graph. It is used for PREDICT and by the
      # `logging_hook`.
      "probabilities": tf.nn.softmax(logits, name="softmax_tensor")
  }

  if mode == tf.estimator.ModeKeys.PREDICT:
    return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)

  # Calculate Loss (for both TRAIN and EVAL modes)
  loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)

  # Configure the Training Op (for TRAIN mode)
  if mode == tf.estimator.ModeKeys.TRAIN:
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
    train_op = optimizer.minimize(
        loss=loss,
        global_step=tf.train.get_global_step())
    return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)

  # Add evaluation metrics (for EVAL mode)
  eval_metric_ops = {
      "accuracy": tf.metrics.accuracy(
          labels=labels, predictions=predictions["classes"])}
  return tf.estimator.EstimatorSpec(
      mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)